---
- name: Install puppet repo
yum: name=http://yum.puppetlabs.com/puppetlabs-release-el-{{ ansible_lsb.major_release }}.noarch.rpm state=present
- name: Install puppet agent
  yum: pkg=puppet state=latest
